INSERT INTO guia.dbo.Arquetipos (Numero,Nombre,LetraHebrea,SignificadoEsoterico,Mensaje,ElementoOPlaneta,ImagenUrl) VALUES
	 (1,N'Independencia',N'א (Alef)',N'Representa el inicio, la autosuficiencia, el ser anfitrión y la unidad. Es el potencial absoluto antes de manifestarse.',N'Potencialidad pura y liderazgo.',N'Fuego / Sol',N'/img/arquetipos/arquetipo1.jpg'),
	 (2,N'Dualidad',N'ב (Bet)',N'Simboliza la intuición, el secreto y el reconocimiento en el otro. Es el útero que recibe y la dependencia necesaria para el equilibrio.',N'El espejo, la pareja y la recepción.',N'Luna',N'/img/arquetipos/arquetipo2.jpg'),
	 (3,N'Intelecto',N'ג (Guímel)',N'Representa al Artífice, el padre ideológico y el conocimiento racional. Es la mente, la cabeza y la capacidad de explicar el mundo.',N'Creación mental y comunicación.',N'Mercurio',N'/img/arquetipos/arquetipo3.jpg'),
	 (4,N'Estructura',N'ד (Dálet)',N'Simboliza el mundo físico, la casa y el cuerpo. Es la precisión, la organización y el útero que da forma a la realidad tangible.',N'Solidez, cimientos y raíces.',N'Tierra',N'/img/arquetipos/arquetipo4.jpg'),
	 (5,N'Coherencia',N'ה (He)',N'Representa al director de equipo que une pensar, hablar y hacer. Es la moral, el orden y el elemento humano o quinto elemento.',N'Liderazgo ético y marco de vida.',N'Hierro / Marte',N'/img/arquetipos/arquetipo5.jpg'),
	 (6,N'Conexión',N'ו (Vav)',N'Simboliza la niñez, el puente de comunicación y el remate de las ideas. Representa la sensualidad y la alegría de ser humano.',N'Inocencia, juego y creación.',N'Venus',N'/img/arquetipos/arquetipo6.jpg'),
	 (7,N'Acción',N'ז (Zayin)',N'Representa el triunfo, la toma de decisiones y la capacidad de colonizar. Es la energía que fecunda y avanza hacia objetivos claros.',N'Control, conquista y determinación.',N'Marte',N'/img/arquetipos/arquetipo7.jpg'),
	 (8,N'Sabiduría',N'ח (Jet)',N'Simboliza la ley, el territorio y la estrategia. Es la sabiduría aplicada a la familia, el dinero y el equilibrio de la sangre.',N'Poder, justicia y planificación.',N'Saturno',N'/img/arquetipos/arquetipo8.jpg'),
	 (9,N'Buscador',N'ט (Tet)',N'Representa al guía y orientador. Es la sabiduría del solitario, la conexión con los números y la búsqueda de soluciones profundas.',N'Experimentación e iluminación interna.',N'Neptuno',N'/img/arquetipos/arquetipo9.jpg'),
	 (10,N'Oportunidad',N'י (Yod)',N'Simboliza el movimiento y el sentido de unidad con lo superior a través del Árbol de la Vida. Representa la riqueza y estabilidad divina.',N'Cambio, suerte y abundancia.',N'Júpiter',N'/img/arquetipos/arquetipo10.jpg');
INSERT INTO guia.dbo.Arquetipos (Numero,Nombre,LetraHebrea,SignificadoEsoterico,Mensaje,ElementoOPlaneta,ImagenUrl) VALUES
	 (11,N'Fuerza',N'כ (Kaf)',N'Representa el principio de la secuencia creadora material. Es la energía de la marca y la fuerza necesaria para sostener la realidad.',N'Coraje, marca y autoconfianza.',N'Sol',N'/img/arquetipos/arquetipo11.jpg'),
	 (12,N'El Colgado',N'Lamed',N'Representa la pausa necesaria antes de un gran cambio espiritual. No es una derrota, es una elección de ver la verdad.',N'Es tiempo de detenerse y mirar desde otra perspectiva. El sacrificio de hoy es la sabiduría de mañana.',N'Neptuno / Agua',N'/images/arquetipos/12.jpg'),
	 (13,N'Transformación',N'מ (Mem)',N'Simboliza morir antes de morir para renacer. Es la escalera hacia la espiritualidad y el cambio profundo de la conciencia.',N'Amor, unidad y cambio de estado.',N'Agua',N'/img/arquetipos/arquetipo13.jpg'),
	 (14,N'Suficiencia',N'נ (Nun)',N'Representa la oración, el soltar y el cerrar acuerdos. Es la capacidad de usar la tecnología y comunicación para la libertad espiritual.',N'Liberación del alma y abundancia.',N'Aire',N'/img/arquetipos/arquetipo14.jpg'),
	 (15,N'El Imán',N'Sámej (ס)',N'Representa el poder de atracción, el carisma y los deseos profundos. Es la fuerza que nos vincula a la materia, la sexualidad y la capacidad de seducción para materializar.',N'Magnetismo, pasión y sombra.',N'Fuego',N'/img/arquetipos/arquetipo15.jpg'),
	 (16,N'La Ruptura',N'Ayin (ע)',N'Simboliza la eliminación de lo que ya no sirve. Es la torre que se rompe para liberar la verdad, permitiendo que la energía estancada fluya de nuevo hacia la construcción de algo real.',N'Liberación y caída de estructuras.',N'Marte / Urano',N'/img/arquetipos/arquetipo16.jpg'),
	 (17,N'La Esperanza',N'Pe (פ)',N'Representa la luz en el camino y la conexión con el propósito divino. Es el arquetipo de la transparencia, la sanación y la confianza en que el universo provee lo necesario.',N'Inspiración, fe y guía estelar.',N'Aire / Acuario',N'/img/arquetipos/arquetipo17.jpg'),
	 (18,N'Tradición',N'צ (Tsadi)',N'Representa el origen, los sueños y los registros akáshicos. Es la investigación de los secretos del inconsciente familiar.',N'Pasado, imaginación y raíces familiares.',N'Luna',N'/img/arquetipos/arquetipo18.jpg'),
	 (19,N'Claridad',N'ק (Kof)',N'Representa la autoridad moral, la paz y la confianza absoluta. Es el Sol que brinda abundancia y luz al propósito de vida.',N'Éxito, armonía y felicidad.',N'Sol',N'/img/arquetipos/arquetipo19.jpg'),
	 (20,N'El Despertar',N'Resh (ר)',N'Representa la resurrección de ideas, el juicio constructivo y la liberación de patrones antiguos. Es el despertar a una nueva realidad espiritual.',N'Renovación y llamado de la conciencia.',N'Fuego / Saturno',N'/img/arquetipos/arquetipo20.jpg');
INSERT INTO guia.dbo.Arquetipos (Numero,Nombre,LetraHebrea,SignificadoEsoterico,Mensaje,ElementoOPlaneta,ImagenUrl) VALUES
	 (21,N'Visión Global',N'Shin (ש)',N'Simboliza la totalidad, el éxito y la belleza. Es la capacidad de ver el mundo como un todo integrado, logrando la plenitud y la valentía creativa.',N'Logro, integración y armonía global.',N'Totalidad',N'/img/arquetipos/arquetipo21.jpg'),
	 (22,N'Trascendencia',N'Tav (ת)',N'Representa la capacidad de traspasar límites y la autoconfianza absoluta. Es el arquetipo del genio que manifiesta grandes ideas y proyectos fuera de lo común.',N'Genio, originalidad y grandes retos.',N'Plutón',N'/img/arquetipos/arquetipo22.jpg'),
	 (26,N'Gestión de Crisis',N'Yod-Vav (יה)',N'Este es un arquetipo de puestos especiales. Simboliza la capacidad de ''bajar al fango'' en situaciones difíciles y realizar una función mesiánica o transformadora.',N'Intervención especial y milagros.',N'Aspectos del 8',N'/img/arquetipos/arquetipo26.jpg'),
	 (33,N'Amor Universal',N'Lamed-Alef (לא)',N'Representa el grado más alto de conexión humana. Es la guía desde el amor puro, la sanación a través de la risa y el remate perfecto de la creación humana.',N'Entrega incondicional y servicio.',N'Aspectos del 6',N'/img/arquetipos/arquetipo33.jpg');
