INSERT INTO guia.dbo.RetosSemanales (Titulo,Descripcion,Instrucciones,NumeroAsociado,TemaId,FechaInicio,FechaFin,Activo,EsGlobal,Dificultad) VALUES
	 (N'El Camino de la Paz',N'Hoy respira profundo 3 veces cuando sientas estrés.',N'Cierra los ojos, inhala en 4 tiempos, mantén 4 y exhala en 4. Hazlo tres veces seguidas.',NULL,1,'2026-04-28 11:22:35.3874980',NULL,1,1,N'Básico'),
	 (N'Frecuencia de Alegría',N'Escribe 3 cosas que te hicieron sonreír hoy.',N'Al final del día, busca tres momentos pequeños (un café, una charla, un paisaje) y regístralos en tu bitácora.',NULL,1,'2026-04-28 11:22:35.3875750',NULL,1,1,N'Básico'),
	 (N'Anclaje de Tierra',N'Identifica 5 cosas que puedes ver ahora mismo.',N'Usa la técnica 5-4-3-2-1: Nombra 5 cosas que ves, 4 que tocas, 3 que oyes, 2 que hueles y 1 que saboreas para salir de tu mente y volver al presente.',NULL,1,'2026-04-28 11:22:35.3875760',NULL,1,1,N'Básico'),
	 (N'Luz de Gratitud',N'Agradece algo que hoy das por sentado.',N'Piensa en algo básico: el agua caliente, tus zapatos, o tu conexión a internet. Escribe por qué ese pequeño detalle hace tu vida más fácil hoy.',NULL,1,'2026-04-28 11:22:35.3875770',NULL,1,1,N'Básico'),
	 (N'Movimiento Consciente',N'Camina 10 minutos sin mirar el celular.',N'Sal a caminar. El objetivo no es llegar a un sitio, sino sentir cómo tus pies tocan el suelo y cómo el aire entra en tus pulmones. Observa tu entorno en silencio.',NULL,1,'2026-04-28 11:22:35.3875810',NULL,1,1,N'Básico'),
	 (N'Vínculo de Oro',N'Envía un mensaje de aprecio a alguien que no esperas.',N'Elige a un amigo o familiar y dile: ''Me acordé de ti y quería decirte que valoro tu presencia''. No esperes nada a cambio, solo entrega esa frecuencia.',NULL,1,'2026-04-28 11:22:35.3875830',NULL,1,1,N'Básico'),
	 (N'Silencio Sagrado',N'Pasa 5 minutos en silencio total al despertar.',N'Antes de tocar el celular o prender la TV, quédate sentado en tu cama. Solo observa tus pensamientos sin juzgarlos. Eres el observador, no el pensamiento.',NULL,1,'2026-04-28 11:22:35.3875840',NULL,1,1,N'Básico'),
	 (N'El Observador en el Faro',N'Hoy no tomes decisiones importantes, solo observa.',N'Cuando te sientas perdido, imagina que eres un faro. Las olas (problemas) vienen y van, pero el faro no se mueve. Dedica 5 minutos a ver tus dudas como si no fueran tuyas, solo como nubes pasando.',NULL,1,'2026-04-28 11:22:35.3875880',NULL,1,1,N'Básico'),
	 (N'La Carta al Futuro',N'Escribe una frase sobre quién quieres ser en un año.',N'Esa sensación de que ''algo falta'' es tu ''yo'' del futuro llamándote. Escribe en tu bitácora una sola frase que empiece con: ''Estoy listo para recibir...'', y deja que el universo trabaje el resto.',NULL,1,'2026-04-28 11:22:35.3875880',NULL,1,1,N'Básico'),
	 (N'Sincronicidad Visual',N'Busca patrones en los números de hoy.',N'Durante el día, presta atención a las matrículas, relojes o precios. Si ves números repetidos o tu número de vida, anótalo. Es la confirmación de que hay un orden mayor guiándote.',NULL,1,'2026-04-28 11:22:35.3875890',NULL,1,1,N'Básico');
INSERT INTO guia.dbo.RetosSemanales (Titulo,Descripcion,Instrucciones,NumeroAsociado,TemaId,FechaInicio,FechaFin,Activo,EsGlobal,Dificultad) VALUES
	 (N'El Escudo de Agua',N'Visualiza el enojo resbalando por tu cuerpo.',N'Si algo sale mal con los servidores o clientes, antes de reaccionar, bebe un vaso de agua lentamente. Imagina que el agua apaga el fuego interno y que las palabras de los demás no pueden mojarte.',NULL,1,'2026-04-28 11:22:35.3875890',NULL,1,1,N'Básico');
