// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace Credito.BDD.Tests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::Xunit.TraitAttribute("Category", "allure.suite:Credito")]
    [global::Xunit.TraitAttribute("Category", "allure.subSuite:CasosBorde")]
    public partial class EvaluacionDeCredito_CasosDeBordeFeature : object, global::Xunit.IClassFixture<EvaluacionDeCredito_CasosDeBordeFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "allure.suite:Credito",
                "allure.subSuite:CasosBorde"};
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("es"), "Features", "Evaluación de Crédito - Casos de Borde", "  Como sistema de evaluación crediticia\r\n  Quiero validar los criterios de casos " +
                "de borde\r\n  Para garantizar una correcta asignación y seguridad del proceso.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CasosBorde.feature"
#line hidden
        
        public EvaluacionDeCredito_CasosDeBordeFeature(EvaluacionDeCredito_CasosDeBordeFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/CasosBorde.feature.ndjson", 7);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Cliente con edad mínima permitida (ej. 18 años)")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Evaluación de Crédito - Casos de Borde")]
        [global::Xunit.TraitAttribute("Description", "Cliente con edad mínima permitida (ej. 18 años)")]
        public async global::System.Threading.Tasks.Task ClienteConEdadMinimaPermitidaEj_18Anos()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cliente con edad mínima permitida (ej. 18 años)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 9
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 10
    await testRunner.GivenAsync("que el cliente tiene una edad de 18 años", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 11
    await testRunner.WhenAsync("el sistema procesa la solicitud de evaluación de crédito", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 12
    await testRunner.ThenAsync("el resultado debe ser: \"Crédito asignado si cumple demás criterios\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Cliente con edad máxima permitida (ej. 70 años)")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Evaluación de Crédito - Casos de Borde")]
        [global::Xunit.TraitAttribute("Description", "Cliente con edad máxima permitida (ej. 70 años)")]
        public async global::System.Threading.Tasks.Task ClienteConEdadMaximaPermitidaEj_70Anos()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cliente con edad máxima permitida (ej. 70 años)", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 14
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
    await testRunner.GivenAsync("que el cliente tiene una edad de 70 años", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 16
    await testRunner.WhenAsync("el sistema procesa la solicitud de evaluación de crédito", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 17
    await testRunner.ThenAsync("el resultado debe ser: \"Crédito asignado si cumple demás criterios\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Ingreso justo en el umbral mínimo requerido")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Evaluación de Crédito - Casos de Borde")]
        [global::Xunit.TraitAttribute("Description", "Ingreso justo en el umbral mínimo requerido")]
        public async global::System.Threading.Tasks.Task IngresoJustoEnElUmbralMinimoRequerido()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Ingreso justo en el umbral mínimo requerido", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 19
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
    await testRunner.GivenAsync("que el cliente tiene ingresos exactamente en el umbral mínimo", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 21
    await testRunner.WhenAsync("el sistema procesa la solicitud de evaluación de crédito", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 22
    await testRunner.ThenAsync("el resultado debe ser: \"Crédito aprobado si no hay otras restricciones\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Cliente con historial crediticio vacío")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Evaluación de Crédito - Casos de Borde")]
        [global::Xunit.TraitAttribute("Description", "Cliente con historial crediticio vacío")]
        public async global::System.Threading.Tasks.Task ClienteConHistorialCrediticioVacio()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cliente con historial crediticio vacío", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 24
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 25
    await testRunner.GivenAsync("que el cliente no cuenta con registros previos en su historial crediticio", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 26
    await testRunner.WhenAsync("el sistema procesa la solicitud de evaluación de crédito", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 27
    await testRunner.ThenAsync("el resultado debe ser: \"Evaluación especial / crédito limitado\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Cliente con deuda exactamente igual al límite permitido")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Evaluación de Crédito - Casos de Borde")]
        [global::Xunit.TraitAttribute("Description", "Cliente con deuda exactamente igual al límite permitido")]
        public async global::System.Threading.Tasks.Task ClienteConDeudaExactamenteIgualAlLimitePermitido()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Cliente con deuda exactamente igual al límite permitido", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 29
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 30
    await testRunner.GivenAsync("que el cliente posee una deuda exactamente igual al límite permitido", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dado ");
#line hidden
#line 31
    await testRunner.WhenAsync("el sistema procesa la solicitud de evaluación de crédito", ((string)(null)), ((global::Reqnroll.Table)(null)), "Cuando ");
#line hidden
#line 32
    await testRunner.ThenAsync("el resultado debe ser: \"Crédito aprobado con condiciones\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Entonces ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await EvaluacionDeCredito_CasosDeBordeFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await EvaluacionDeCredito_CasosDeBordeFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
